base_model = "google/gemini-3.5-flash"
name = "Gemini 3.5 Flash (Vertex AI, EU)"

[[reasoning_options]]
type = "effort"
values = ["minimal", "low", "medium", "high"]

[cost]
input = 1.5
output = 9
reasoning = 9
cache_read = 0.15
cache_write = 0.083333
input_audio = 3
