base_model = "google/gemini-3.1-pro-preview"
name = "Gemini Pro Latest (Gemini 3.1 Pro Preview, Vertex AI)"

[[reasoning_options]]
type = "effort"
values = ["low", "medium", "high"]

[cost]
input = 2
output = 12
reasoning = 12
cache_read = 0.2
cache_write = 0.375
input_audio = 2

[[cost.tiers]]
tier = { type = "context", size = 200_000 }
input = 4
output = 18
cache_read = 0.4
cache_write = 0.25
