base_model = "alibaba/qwen3.8-max-0902"
structured_output = true

[[reasoning_options]]
type = "effort"
values = ["none", "low", "medium", "high", "max"]

[cost]
input = 2
output = 6
cache_read = 0.17
cache_write = 2.5

[limit]
context = 991_808
input = 991_808
