base_model = "openai/gpt-oss-120b"
release_date = "2026-04-13"
last_updated = "2026-07-22"

[[reasoning_options]]
type = "effort"
values = ["low", "medium", "high"]

[cost]
input = 0.16332
output = 0.65328
cache_read = 0.015243

[limit]
output = 13_107
