base_model = "nvidia/nemotron-3-ultra-550b-a55b"
name = "Nemotron 3 Ultra 550B A55B (Deep Infra)"
structured_output = true

[[reasoning_options]]
type = "effort"
values = ["none", "medium", "high"]

[cost]
input = 0.5
output = 2.2
cache_read = 0.1

[limit]
context = 262_144
