base_model = "meta/llama-3.3-70b-instruct"
name = "Llama-3.3-70B-Instruct (Nebius)"
attachment = false
structured_output = true

[cost]
input = 0.13
output = 0.4
cache_read = 0.13

[limit]
context = 131_072
