base_model = "alibaba/qwen2.5-coder-32b-instruct"
name = "Qwen2.5-Coder-32B-Instruct (Cloudflare)"
tool_call = false
structured_output = false

[cost]
input = 0.66
output = 1

[limit]
context = 32_768
