base_model = "zhipuai/glm-4.7-flash"
name = "GLM-4.7-Flash (Deep Infra)"
structured_output = true
reasoning_options = []

[cost]
input = 0.06
output = 0.4
cache_read = 0.01

[limit]
context = 202_752
