base_model = "stepfun/step-3.7-flash"
base_model_omit = ["limit.input"]
name = "Step 3.7 Flash (Deep Infra)"
structured_output = true

[[reasoning_options]]
type = "effort"
values = ["low", "medium", "high"]

[cost]
input = 0.2
output = 1.15
cache_read = 0.04

[limit]
context = 262_144
