base_model = "stepfun/step-3.5-flash"
base_model_omit = ["limit.input"]
name = "Step 3.5 Flash (Deep Infra)"
structured_output = true

[[reasoning_options]]
type = "effort"
values = ["low", "high"]

[cost]
input = 0.09
output = 0.3
cache_read = 0.02

[limit]
context = 262_144
