base_model = "deepseek/deepseek-v4-pro-0813"
tool_call = false
structured_output = false

[[reasoning_options]]
type = "effort"
values = ["none", "low", "high", "max"]

[cost]
input = 1.3
output = 2.6
cache_read = 0.1

[limit]
context = 1_048_576
