base_model = "openai/gpt-oss-20b"
name = "GPT OSS 20B (Cloudflare)"
structured_output = false

[[reasoning_options]]
type = "effort"
values = ["low", "medium", "high"]

[cost]
input = 0.2
output = 0.3

[limit]
context = 128_000
