base_model = "tencent/hy3"
base_model_omit = ["limit.input"]
name = "Hy3 (Deep Infra)"
structured_output = true

[[reasoning_options]]
type = "effort"
values = ["none", "low", "high"]

[cost]
input = 0.14
output = 0.58
cache_read = 0.035

[limit]
context = 262_144
