base_model = "openai/gpt-oss-120b"
name = "GPT OSS 120B (Fireworks AI)"
structured_output = false

[[reasoning_options]]
type = "effort"
values = ["low", "medium", "high"]

[cost]
input = 0.15
output = 0.6
cache_read = 0.014
