base_model = "meta/llama-3.2-11b-vision-instruct"
name = "Llama-3.2-11B-Vision-Instruct (Deep Infra)"
tool_call = false
structured_output = true

[cost]
input = 0.345
output = 0.345

[limit]
context = 131_072
