base_model = "openai/gpt-oss-120b"
name = "GPT OSS 120B (Scaleway)"
structured_output = false

[[reasoning_options]]
type = "effort"
values = ["low", "medium", "high"]

[cost]
input = 0.17433
output = 0.69732

[limit]
context = 128_000
