base_model = "openai/gpt-oss-120b"
structured_output = false

[[reasoning_options]]
type = "effort"
values = ["low", "medium", "high"]

[cost]
input = 0.173505
output = 0.69402

[limit]
context = 128_000
