base_model = "moonshotai/kimi-k2.5"
name = "Kimi K2.5 (TensorX)"
structured_output = false
reasoning_options = []

[cost]
input = 0.5
output = 2.8
cache_read = 0.125

[modalities]
input = ["text", "image"]
