base_model = "openai/gpt-oss-120b"
name = "GPT OSS 120B (IONOS)"
tool_call = false
structured_output = false

[[reasoning_options]]
type = "effort"
values = ["low", "medium", "high"]

[cost]
input = 0.17433
output = 0.75543
