base_model = "nvidia/nemotron-3-super-120b-a12b"
name = "Nemotron 3 Super 120B A12B (Nebius)"
structured_output = true

[[reasoning_options]]
type = "effort"
values = ["none", "low", "medium"]

[cost]
input = 0.3
output = 0.9
cache_read = 0.3
