name = "DeepSeek V4 Flash Latest"
description = "This model always redirects to the latest model in the DeepSeek V4 Flash family."
family = "deepseek"
release_date = "2026-08-01"
last_updated = "2026-08-01"
attachment = false
reasoning = true
temperature = true
tool_call = true
structured_output = true
open_weights = false

[[reasoning_options]]
type = "effort"
values = ["none", "low", "high", "max"]

[cost]
input = 0.045
output = 0.09
cache_read = 0.009

[limit]
context = 1_048_576
output = 943_718

[modalities]
input = ["text"]
output = ["text"]
