base_model = "openai/gpt-5.1-codex-mini"
base_model_omit = ["limit.input"]
name = "GPT-5.1 Codex mini (Azure)"

[[reasoning_options]]
type = "effort"
values = ["none", "low", "medium", "high"]

[cost]
input = 0.25
output = 2
cache_read = 0.025

[limit]
context = 272_000

[modalities]
input = ["text", "image", "pdf"]
