# Toggle: reasoning.enabled = true|false
# https://openrouter.ai/docs/guides/best-practices/reasoning-tokens
base_model = "deepseek/deepseek-v4-pro-0813"

[[reasoning_options]]
type = "toggle"

[[reasoning_options]]
type = "effort"
values = ["low", "high", "max"]

[cost]
input = 1.12068
output = 3.36204
cache_read = 0.037356

[limit]
context = 1_048_576
