# Toggle: reasoning.enabled = true|false
# https://openrouter.ai/docs/guides/best-practices/reasoning-tokens
base_model = "deepseek/deepseek-v4-flash-0731"

[[reasoning_options]]
type = "toggle"

[[reasoning_options]]
type = "effort"
values = ["low", "high", "max"]

[cost]
input = 0.04998
output = 0.09996
cache_read = 0.009996

[limit]
context = 1_310_720
output = 131_072
