# Toggle: reasoning.enabled = true|false
# https://openrouter.ai/docs/guides/best-practices/reasoning-tokens
base_model = "deepseek/deepseek-v4-pro-0813"

[[reasoning_options]]
type = "toggle"

[[reasoning_options]]
type = "effort"
values = ["low", "high", "max"]

[cost]
input = 0.57948
output = 1.73844
cache_read = 0.019316

[limit]
context = 1_048_576
