base_model = "nvidia/nemotron-3-super-120b-a12b"
name = "Nemotron 3 Super 120B A12B (FlexAI)"
tool_call = false
structured_output = false

[[reasoning_options]]
type = "effort"
values = ["none", "low", "medium"]

[cost]
input = 0.085
output = 0.4
